#!/bin/bash

echo "Downloading fastfetch..."
curl -Ls -o fastfetch.tar.gz https://github.com

if [ ! -s fastfetch.tar.gz ]; then
    echo "Error: Download failed (file is empty)"
    exit 1
fi

echo "Unzipping..."
tar -xzf fastfetch.tar.gz

echo "Installing..."
cp -f fastfetch-*/usr/bin/fastfetch /usr/bin/fastfetch
chmod +x /usr/bin/fastfetch

echo "Done!"
